# =========================
# SERVER
# =========================

server.port=8080


# =========================
# DATABASE
# =========================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true


# =========================
# AWS
# =========================

aws.access.key=YOUR_AWS_KEY
aws.secret.key=YOUR_AWS_SECRET
aws.region=ap-south-1


# =========================
# GEMINI AI
# =========================

gemini.api.key=YOUR_GEMINI_KEY


# =========================
# EMAIL
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=YOUR_GMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true